defaults:
  - model: moderncamembert_base
  - _self_

paths:
  data_dir: ${hydra:runtime.cwd}/data
  splits_dir: ${hydra:runtime.cwd}/data/splits
  models_dir: ${hydra:runtime.cwd}/models
  results_dir: ${hydra:runtime.cwd}/benchmark/results

training:
  num_epochs: 5
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  seed: 42
  batch_size: 16
  max_length: 512

evaluation:
  metric: seqeval
  average: weighted

wandb:
  project: onco-ner
  entity: "jeaneudes-gbada"